apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper-helm
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    chart: gatekeeper
    repoURL: https://open-policy-agent.github.io/gatekeeper/charts
    targetRevision: 3.8.1
    helm:
      releaseName: gatekeeper-release
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gatekeeper-system
