apiVersion: batch/v1
kind: Job
metadata:
  generateName: check-cert-manager-
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: check-cert-manager
        image: busybox
        command:
          - "true"
      restartPolicy: Never
  backoffLimit: 0
