apiVersion: batch/v1
kind: Job
metadata:
  generateName: check-gatekeeper-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: check-gatekeeper
        image: busybox
        command:
          - "true"
      restartPolicy: Never
  backoffLimit: 0
